export const DOGS_LIST = [
  "Labrador Retriever",
  "Pastor Alemán",
  "Golden Retriever",
  "Bulldog Francés",
  "Bulldog Inglés",
  "Poodle",
  "Beagle",
  "Rottweiler",
  "Dachshund",
  "Yorkshire Terrier",
  "Boxer",
  "Husky Siberiano",
  "Doberman",
  "Shih Tzu",
  "Pomerania",
  "Chihuahua",
  "Cocker Spaniel",
  "Border Collie",
  "Maltés",
  "Gran Danés",
  "San Bernardo",
  "Akita Inu",
  "Basset Hound",
  "Shar Pei",
  "Pug",
  "Pitbull",
  "Weimaraner",
  "Samoyedo",
  "Chow Chow",
  "Whippet",
  "Pointer",
  "Galgo Español",
  "Alaskan Malamute",
  "Terranova",
  "Caniche Toy",
  "Fox Terrier",
  "Boston Terrier",
  "Pastor Belga",
  "Cane Corso",
  "Airedale Terrier",
];
